import type { OptionsFormDefinition } from '@/types'

const options = {
    general: [
        {
            help: null,
            disable_if: [],
            hide_if: [],
            label: 'Some static text',
            kind: 'static_text',
            name: 'static',
            text: '',
        },
        {
            help: null,
            disable_if: [],
            hide_if: [],
            label: 'Multiline Text',
            kind: 'textarea',
            name: 'input',
            required: true,
            default: 'default text',
            placeholder: null,
        },
        {
            help: null,
            disable_if: [],
            hide_if: [],
            kind: 'checkbox',
            name: 'chk',
            left_label: 'Left label',
            right_label: null,
            required: false,
            selected: false,
        },
        {
            help: null,
            disable_if: [],
            hide_if: [],
            label: 'My Radio Group',
            kind: 'radio_group',
            name: 'radio',
            options: [
                {
                    label: 'Option 1',
                    value: 'RADIO_1',
                    selected: false,
                },
                {
                    label: 'Option 2',
                    value: 'RADIO_2',
                    selected: true,
                },
            ],
            required: false,
        },
        {
            help: null,
            disable_if: [],
            hide_if: [],
            label: 'My select box',
            kind: 'select',
            name: 'my_select',
            multiple: false,
            options: [
                {
                    label: 'Option 1',
                    value: 'OPT_1',
                    selected: false,
                },
                {
                    label: 'Option 2',
                    value: 'OPT_2',
                    selected: true,
                },
            ],
            required: false,
        },
        {
            help: null,
            disable_if: [],
            hide_if: [],
            label: 'My select box (multi)',
            kind: 'select',
            name: 'my_select_multi',
            multiple: true,
            options: [
                {
                    label: 'Option 1',
                    value: 'OPT_1',
                    selected: true,
                },
                {
                    label: 'Option 2',
                    value: 'OPT_2',
                    selected: false,
                },
                {
                    label: 'Option 3',
                    value: 'OPT_3',
                    selected: true,
                },
            ],
            required: false,
        },
        {
            disable_if: [],
            hide_if: [],
            kind: 'hidden',
            name: 'my_hidden',
            value: 'foo',
        },
        {
            kind: 'repetition',
            name: 'my_repetition',
            initial_repetitions: 2,
            minimum_repetitions: 1,
            increment: 1,
            button_label: null,
            elements: [
                {
                    kind: 'id',
                    name: 'id',
                },
                {
                    help: null,
                    disable_if: [],
                    hide_if: [],
                    label: 'Participant #{ qpy:repno } Role:',
                    kind: 'select',
                    name: 'role',
                    multiple: false,
                    options: [
                        {
                            label: 'Option 1',
                            value: 'OPT_1',
                            selected: true,
                        },
                        {
                            label: 'Option 2',
                            value: 'OPT_2',
                            selected: false,
                        },
                    ],
                    required: false,
                },
                {
                    help: null,
                    disable_if: [],
                    hide_if: [],
                    label: 'Name',
                    kind: 'group',
                    name: 'name',
                    elements: [
                        {
                            help: null,
                            disable_if: [],
                            hide_if: [],
                            label: 'First Name',
                            kind: 'input',
                            name: 'first_name',
                            required: false,
                            default: 'Jane',
                            placeholder: null,
                        },
                        {
                            help: null,
                            disable_if: [],
                            hide_if: [],
                            label: 'Last Name',
                            kind: 'input',
                            name: 'last_name',
                            required: false,
                            default: '',
                            placeholder: null,
                        },
                    ],
                },
            ],
        },
        {
            help: null,
            disable_if: [],
            hide_if: [],
            kind: 'checkbox',
            name: 'has_name',
            left_label: null,
            right_label: 'I have a name.',
            required: false,
            selected: false,
        },
        {
            help: null,
            disable_if: [
                {
                    kind: 'is_not_checked',
                    name: 'has_name',
                },
            ],
            hide_if: [],
            label: 'Name',
            kind: 'group',
            name: 'name_group',
            elements: [
                {
                    help: null,
                    disable_if: [],
                    hide_if: [],
                    label: 'First Name',
                    kind: 'input',
                    name: 'first_name',
                    required: false,
                    default: null,
                    placeholder: null,
                },
                {
                    help: null,
                    disable_if: [],
                    hide_if: [],
                    label: 'Last Name',
                    kind: 'input',
                    name: 'last_name',
                    required: false,
                    default: null,
                    placeholder: null,
                },
            ],
        },
    ],
    sections: [
        {
            name: 'another_section',
            header: 'Another section',
            elements: [
                {
                    help: null,
                    disable_if: [],
                    hide_if: [],
                    label: 'Another static text',
                    kind: 'static_text',
                    name: 'static',
                    text: 'Lorem ipsum dolor sit amet',
                },
                {
                    help: null,
                    disable_if: [],
                    hide_if: [],
                    label: 'Another input',
                    kind: 'input',
                    name: 'some_input',
                    required: true,
                    default: null,
                    placeholder: null,
                },
            ],
        },
    ],
} satisfies OptionsFormDefinition

export default options
