[build-system]
requires = ["poetry-core >=2.0.0, <3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "questionpy-sdk"
description = "Library and toolset for the development of QuestionPy packages"
license = "MIT"
urls = { homepage = "https://questionpy.org" }
version = "0.6.0"
authors = [
    { name = "TU Berlin innoCampus" },
    { email = "info@isis.tu-berlin.de" }
]
requires-python = ">=3.12, <4.0"
dependencies = [
    "click >=8.2.0, <9.0.0",
    "aiohttp >=3.11.18, <4.0.0",
    "pydantic >=2.11.4, <3.0.0",
    "PyYAML >=6.0.2, <7.0.0",
    "questionpy-server @ git+https://github.com/questionpy-org/questionpy-server.git@789c473f44d1166f27a04e286175b17b132696f8",
    "jinja2 >=3.1.6, <4.0.0",
    "aiohttp-jinja2 >=1.6, <2.0",
    "lxml[html-clean] >=5.4.0, <5.5.0",
    "babel >=2.17.0, <3.0.0",
    "pathspec >=0.12.1, <0.13.0",
    "yarl (>=1.20.1,<2.0.0)"
]

[tool.poetry.group.dev.dependencies]
types-PyYAML = ">=6.0.12.20250516, <7.0.0"
types-psutil = ">=7.0.0.20250516, <8.0.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = ">= 8.3.5, <9.0.0"
pytest-aiohttp = ">= 1.1.0, <2.0.0"
pytest-md = ">=0.2.0, <0.3.0"
coverage = { extras = ["toml"], version = ">=7.8.0, <8.0.0" }
lxml-stubs = ">=0.5.1, <0.6.0"
pytest-archon = ">=0.0.6, <0.1.0"
pytest-asyncio = ">=0.26.0, <0.27.0"
pytest-playwright-asyncio = ">=0.7.0, <0.8.0"
psutil = ">=7.0.0, <8.0.0"

[tool.poetry.group.linter]
dependencies = { ruff = ">=0.11.10, <0.12.0" }
optional = true

[tool.poetry.group.type-checker]
dependencies = { mypy = ">=1.15.0, <2.0.0" }
optional = true

[project.scripts]
questionpy-sdk = "questionpy_sdk.__main__:cli"

[tool.poetry]
packages = [
    { include = "questionpy" },
    { include = "questionpy_sdk" }
]
include = [
    "questionpy_sdk/resources/minimal_example.zip",
    { path = "questionpy_sdk/webserver/static/assets/*", format = ["sdist", "wheel"] },
    { path = "questionpy_sdk/webserver/static/*", format = ["sdist", "wheel"] },
]
requires-poetry = ">=2.0.0, <3.0.0"

[tool.poetry.build]
generate-setup-file = false
script = "build.py"

[tool.ruff]
extend = "ruff_defaults.toml"

[tool.ruff.lint.pep8-naming]
extend-ignore-names = ["mcs", "test_*"]

[tool.ruff.lint.extend-per-file-ignores]
# Allow f-string without an `f` prefix for our custom error formatter.
"**/questionpy_sdk/webserver/controllers/attempt/errors.py" = ["RUF027"]
# unused-async (aiohttp handlers must be async even if they don't use it)
"**/questionpy_sdk/webserver/routes/*" = ["RUF029"]

[tool.ruff.lint.pylint]
allow-dunder-method-names = ["__get_pydantic_core_schema__"]

[tool.pytest.ini_options]
addopts = "--doctest-modules --ignore examples"
markers = ["app_routes", "render_params", "source_pkg", "ui_file"]
# We run E2E tests separately
norecursedirs = "e2e"
# https://github.com/pytest-dev/pytest-asyncio#auto-mode
asyncio_mode = "auto"
# Module scope is recommended: https://pytest-asyncio.readthedocs.io/en/stable/concepts.html#asyncio-event-loops
asyncio_default_test_loop_scope = "module"
asyncio_default_fixture_loop_scope = "module"

# This section is read automatically by Coverage.py when its working directory is .
# https://coverage.readthedocs.io/en/6.5.0/config.html#configuration-reference
[tool.coverage.run]
branch = true
source = ["questionpy", "questionpy_sdk"]
omit = ["questionpy_sdk/webserver/middlewares/vite_dev.py"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "if TYPE_CHECKING:"]

[tool.mypy]
plugins = "pydantic.mypy"
disallow_untyped_defs = true
strict_optional = true
show_error_codes = true
exclude = ["^examples/"]
