/*
 * This file is part of the QuestionPy SDK. (https://questionpy.org)
 * The QuestionPy SDK is free software released under terms of the MIT license. See LICENSE.md.
 * (c) Technische Universität Berlin, innoCampus <info@isis.tu-berlin.de>
 */

// This file was automatically generated by generate-ts-types.py.
// DO NOT MODIFY IT BY HAND. Instead, modify the source Pydantic models, and regenerate this file.

export type AttemptStatus = 'STARTED' | 'IN_PROGRESS' | 'SCORED'
export type ScoringCode = 'AUTOMATICALLY_SCORED' | 'NEEDS_MANUAL_SCORING' | 'RESPONSE_NOT_SCORABLE' | 'INVALID_RESPONSE'
export type RenderError =
    | InvalidAttributeValueError
    | ConversionError
    | PlaceholderReferenceError
    | InvalidCleanOptionError
    | InvalidContentError
    | ExpectedAncestorError
    | UnknownElementError
    | UnknownAttributeError
    | DuplicateNameError
    | XMLSyntaxError
/**
 * Collects render errors and provides a sorted iterator.
 */
export type RenderErrorCollection = RenderError[]

/**
 * Represents the API response data for rendering an attempt in the frontend.
 */
export interface AttemptRenderData {
    attempt_data: AttemptData
    attempt_html: string
    render_errors: SectionErrorMap
}
/**
 * Represents the API response data for an attempt in the frontend.
 */
export interface AttemptData {
    attempt_status: AttemptStatus
    attempt_state: string
    variant: number
    scoring_state?: string | null
    scoring_code?: ScoringCode | null
    score?: number | null
}
/**
 * A mapping of sections to their associated render errors.
 */
export interface SectionErrorMap {
    [k: string]: RenderErrorCollection
}
/**
 * Invalid attribute value(s).
 */
export interface InvalidAttributeValueError {
    template: string
    template_kwargs: TemplateKwargs
    kind: 'invalid_attribute_value'
    type: string
    /**
     * Original line number where the error occurred or None if unknown.
     */
    line: number | null
}
/**
 * A mapping of placeholder keys to values for a template.
 */
export interface TemplateKwargs {
    [k: string]: string | string[]
}
/**
 * Could not convert a value to another type.
 */
export interface ConversionError {
    template: string
    template_kwargs: TemplateKwargs
    kind: 'conversion'
    type: string
    /**
     * Original line number where the error occurred or None if unknown.
     */
    line: number | null
}
/**
 * An unknown or no placeholder was referenced.
 */
export interface PlaceholderReferenceError {
    template: string
    template_kwargs: TemplateKwargs
    kind: 'placeholder_reference'
    type: string
    /**
     * Original line number where the error occurred or None if unknown.
     */
    line: number | null
}
/**
 * Invalid clean option.
 */
export interface InvalidCleanOptionError {
    template: string
    template_kwargs: TemplateKwargs
    kind: 'invalid_clean_option'
    type: string
    /**
     * Original line number where the error occurred or None if unknown.
     */
    line: number | null
}
/**
 * Invalid content placement.
 */
export interface InvalidContentError {
    template: string
    template_kwargs: TemplateKwargs
    kind: 'invalid_content'
    type: string
    /**
     * Original line number where the error occurred or None if unknown.
     */
    line: number | null
}
/**
 * Invalid element placement.
 */
export interface ExpectedAncestorError {
    template: string
    template_kwargs: TemplateKwargs
    kind: 'expected_ancestor'
    type: string
    /**
     * Original line number where the error occurred or None if unknown.
     */
    line: number | null
}
/**
 * Unknown element with qpy-namespace.
 */
export interface UnknownElementError {
    template: string
    template_kwargs: TemplateKwargs
    kind: 'unknown_element'
    type: string
    /**
     * Original line number where the error occurred or None if unknown.
     */
    line: number | null
}
/**
 * Unknown attribute with qpy-namespace.
 */
export interface UnknownAttributeError {
    template: string
    template_kwargs: TemplateKwargs
    kind: 'unknown_attribute'
    type: string
    /**
     * Original line number where the error occurred or None if unknown.
     */
    line: number | null
}
/**
 * Invalid duplicate input name.
 */
export interface DuplicateNameError {
    template: string
    template_kwargs: TemplateKwargs
    kind: 'duplicate_name'
    type: string
    /**
     * Original line number where the error occurred or None if unknown.
     */
    line: number | null
}
/**
 * Syntax error while parsing the XML.
 */
export interface XMLSyntaxError {
    template: string
    template_kwargs: TemplateKwargs
    kind: 'xml_syntax'
    type: string
    /**
     * Original line number where the error occurred or None if unknown.
     */
    line: number | null
}
