/*
 * This file is part of the QuestionPy SDK. (https://questionpy.org)
 * The QuestionPy SDK is free software released under terms of the MIT license. See LICENSE.md.
 * (c) Technische Universität Berlin, innoCampus <info@isis.tu-berlin.de>
 */

// This file was automatically generated by generate-ts-types.py.
// DO NOT MODIFY IT BY HAND. Instead, modify the source Pydantic models, and regenerate this file.

export type OptionsFormDataValue = string | number | boolean | string[] | null

/**
 * Represents the API response data for the question's options state.
 */
export interface OptionsStateResponse {
    data: OptionsFormData
    /**
     * Whether the question is newly created and has not been persisted yet.
     */
    is_new: boolean
}
/**
 * The question's options form data.
 */
export interface OptionsFormData {
    [k: string]: OptionsFormDataValue
}
